# Generated by Django 5.0.4 on 2024-05-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='test_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
